server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://39.105.232.210:3306/cloud?serverTimezone=UTC
     username: root
     password: Zqf9610051212.
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: icu.qfservice.cloud.pojo
